[package]
authors = ["Jose Pérez-Cano"]
name = "day1"
version = "0.1.0"
edition = "2021"
description = "Rust program to solve Advent of Code Day1"

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }
